# Generated by Django 3.1.3 on 2021-01-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorapp', '0003_auto_20201231_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
