# Generated by Django 3.1.3 on 2021-01-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorapp', '0004_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Is_publise',
            field=models.BooleanField(blank=True, default=''),
        ),
    ]
