# Generated by Django 3.1.3 on 2021-01-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorapp', '0007_auto_20210106_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
