# Generated by Django 3.1.3 on 2021-01-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorapp', '0009_auto_20210106_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_date',
            new_name='date',
        ),
    ]
