# Generated by Django 3.0.11 on 2021-01-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorapp', '0015_auto_20210119_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
