# Generated by Django 3.0.11 on 2021-01-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorapp', '0016_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stay',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
